### ISSUE TITLE
[Package submission]: ali

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#101]
### Package description

https://github.com/nakabonne/ali
Generate HTTP load and plot the results in real-time
![0BCD85CC-EBA8-4164-9AA5-4487B3E2F53F](https://user-images.githubusercontent.com/42692274/135750327-b9787330-2e8d-4294-87e8-3661dedb8750.gif)

### Licensing

MIT

### Packages

https://github.com/nakabonne/ali/releases
latest: 
https://github.com/nakabonne/ali/releases/download/v0.7.3/ali_0.7.3_linux_arm64.deb https://github.com/nakabonne/ali/releases/download/v0.7.3/ali_0.7.3_linux_armv7.deb

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.

**Comment by ryanfortner** [comment]
Added
