### ISSUE TITLE
[Package submission]: InfluxDB

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#105]
### Package description

https://github.com/influxdata/influxdb
InfluxDB is an open source time series platform. This includes APIs for storing and querying data, processing it in the background for ETL or monitoring and alerting purposes, user dashboards, and visualizing and exploring the data and more. The master branch on this repo now represents the latest InfluxDB, which now includes functionality for Kapacitor (background processing) and Chronograf (the UI) all in a single binary.

### Licensing

MIT

### Packages

- InfluxDB2:
https://dl.influxdata.com/influxdb/releases/influxdb2-2.0.8-arm64.deb
- InfluxDB:
https://dl.influxdata.com/influxdb/releases/influxdb_1.8.9_arm64.deb
https://dl.influxdata.com/influxdb/releases/influxdb_1.8.9_armhf.deb

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.

**Comment by ryanfortner** [comment]
Added
