### ISSUE TITLE
[Package submission]: Clementine

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#107]
### Package description

https://github.com/clementine-player/Clementine
Clementine is a modern music player and library organizer for Windows, Linux and macOS.

### Licensing

GPL-3.0

### Packages

https://github.com/clementine-player/Clementine/releases/download/1.3.1/clementine_1.3.1.jessie_armhf.deb

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.

**Comment by ryanfortner** [comment]
Added
