### ISSUE TITLE
Compile and test with Fosshost

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#108]
@ryanfortner 
I successfully applied to Fosshost for free VPS for open source projects. We got the following VM.

AArch64 Virtual Private Server
4 vCPU
8GB RAM
24GB SSD

To get started with Fosshost AARCH64, first create an account at https://console.aarch64.com/#/signup.
Fosshost has created a project for us. Please tell me the email you used to register, and I will invite you to join this project.

From now on, we can use Fosshost's VPS as the self-hosted runner of GitHub Actions.

**Comment by ryanfortner** [comment]
> Yes, but the apt repository size is larger than I expected, and the disk space is almost running out.

Is there any way to request more disk space?

**Comment by hmsjy2017** [comment]
> Also, make sure to exit the VM properly by using ctrl ] to exit. If you don't do this then I won't be able to log in without restarting the VM, because only one ssh session is allowed at a time.

I know. But the network of the carrier I use supports IPv6, so I usually connect directly to the IPv6 address through ssh.

**Comment by ryanfortner** [comment]
I think this can be closed now.
