### ISSUE TITLE
Revert to reprepro for repo format

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#109]
Can you explain the reason for changing the format of the apt repository? Most apt repositories do not use this format. I don't think it seems good to put all the packages in the same folder.

**Comment by ryanfortner** [comment]
> Can you explain the reason for changing the format of the apt repository? Most apt repositories do not use this format. I don't think it seems good to put all the packages in the same folder.

The old repository used 'reprepro' to write packages to the repository. However, reprepro has no way to automatically enter the GPG key password. I can't run automated repository syncs without a password flag that enters the passphrase. 

The format I'm currently using *directly* uses the 'gpg' command, which has a --passphrase flag. 

In the future, I think it would be a good idea to separate packages by the letter they start with. I'll work on it.

**Comment by hmsjy2017** [comment]
I found a method.
https://askubuntu.com/questions/560573/reprepro-is-there-any-chance-to-enter-the-passphrase-via-bash-script

**Comment by hmsjy2017** [comment]
@ryanfortner Do you plan to restore the format of the apt repository to the original one?

**Comment by ryanfortner** [comment]
> @ryanfortner Do you plan to restore the format of the apt repository to the original one?

Yes, I am working on it.

**Comment by ryanfortner** [comment]
I made a mistake and accidentally deleted all the debs. I am recloning the repository now. 

It will be a little while before it's back up.

**Comment by ryanfortner** [comment]
I have restored all files to the `reprepro` format. I have pushed changes to the [mirrors](https://github.com/raspbian-addons/mirrors) and the [repo.py script](https://github.com/raspbian-addons/scripts).

I have started syncs to osdn and sourceforge, so all the changes should be available on all the mirrors within the next 24 hours.

**Comment by ryanfortner** [comment]
I'm still looking for a working way to automatically sign the repository without having to enter the passphrase... none of the methods have worked thus far.
