### ISSUE TITLE
GitHub actions automated backups?

### ISSUE THREAD

**Issue by ryanfortner** [raspbian-addons/raspbian-addons#111]
I'd like to create some sort of "backup system" for the repository, to download the entire repository, compressing it, and uploading it on a weekly basis.

I'd like to use github actions for this, but I have no knowledge in it (I'd like to learn though)!

Do you have any ideas @hmsjy2017 ?

**Comment by hmsjy2017** [comment]
To learn how to use GitHub Actions, you can refer to its documentation: https://docs.github.com/en/actions/quickstart
It is explained in detail and I think it might help you.

It is possible to automatically back up the repository. But I want to ask where do you want to store it?

**Comment by ryanfortner** [comment]
> To learn how to use GitHub Actions, you can refer to its documentation: https://docs.github.com/en/actions/quickstart
> 
> It explained the usage in detail and I think it might help you.
> 
> 
> 
> It is possible to automatically back up the repository. But I want to ask where do you want to store it?

Thanks for the link. Maybe we can store it as an 'artifact' of the action that was run?

**Comment by hmsjy2017** [comment]
@ryanfortner I think it is possible to back up the repository to OneDrive (with a free E5 Developer trial account). The method is to use onedriver or rclone to mount OneDrive locally and then automatically execute the backup script.
What do you think?

**Comment by ryanfortner** [comment]
Sure, that sounds good. I don't have a onedrive account though.

**Comment by hmsjy2017** [comment]
@ryanfortner You can apply for an account, which is independent of the personal account. The subscription period is 90 days. As long as you frequently call the OneDrive API, you can automatically renew it. If you want, you can set up a OneDrive index program.
https://developer.microsoft.com/zh-cn/microsoft-365/dev-program

**Comment by ryanfortner** [comment]
i've set up a backup action here: https://github.com/raspbian-addons/backup-archive/blob/main/.github/workflows/artifact.yml

downloading the latest archive can be done from the [actions tab](https://github.com/raspbian-addons/backup-archive/actions)

**Comment by hmsjy2017** [comment]
@ryanfortner However, I found that it does not work properly. It may be due to the limitation of the size of the artifact. I think we can back up the repository to SourceForge.
