### ISSUE TITLE
[Package submission]: n

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#119]
### Package description

https://github.com/tj/n

Node version management

### Licensing

MIT

### Packages

Its essence is a bash script, which is easy to package. So I packaged it into a deb.

https://github.com/hmsjy2017/n-deb-packages/releases/tag/v8.0.0

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.

**Comment by ryanfortner** [comment]
Added
