### ISSUE TITLE
A domain name for our project

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#120]
@ryanfortner I successfully applied for the free domain name raspbian-addons.org from Fosshost for our project. Which name server do you think we need to use? I think Cloudflare might be good.
![B1FDA93A-F6CA-480E-9AA4-87F42BBC6EF0](https://user-images.githubusercontent.com/42692274/139589788-c520c2d5-6ac1-44c3-aeae-1714e0c1d164.jpeg)

**Comment by ryanfortner** [comment]
@hmsjy2017 , cloudflare should be good. I already have a Cloudflare account, I can send you the nameservers, would that be good?

**Comment by hmsjy2017** [comment]
@ryanfortner All right.

**Comment by ryanfortner** [comment]
@hmsjy2017 nameservers are: felicity.ns.cloudflare.com jacqueline.ns.cloudflare.com

**Comment by hmsjy2017** [comment]
Sent.

**Comment by hmsjy2017** [comment]
@ryanfortner I think we'd better enable the Enforce HTTPS option in Pages so that the browser will not warn you of "insecure". In addition, the URL in "About" should also be modified to the new one.

**Comment by hmsjy2017** [comment]
@ryanfortner  It seems impossible. But we can create a subdomain that points to Fosshost VPS so that we can have an additional mirror of the apt repository

**Comment by ryanfortner** [comment]
> @ryanfortner  It seems impossible. But we can create a subdomain that points to Fosshost VPS so that we can have an additional mirror of the apt repository

Do you mind setting up the VPS for a mirror? I can make a subdomain, just let me know what domain to point it to.

**Comment by ryanfortner** [comment]
@hmsjy2017

**Comment by hmsjy2017** [comment]
> Do you mind setting up the VPS for a mirror? 

Of course not.

> I can make a subdomain, (maybe repo.raspbian-addons.org?) just let me know what to point it to.

Since Cloudflare CDN supports IPv6, you only need to create an AAAA record pointing to the VPS.

**Comment by ryanfortner** [comment]
> Since Cloudflare CDN supports IPv6, you only need to create an AAAA record pointing to the VPS.

Are the ports 80 and 443 open? 

I apologize for all the questions, the Fosshost documentation isn't very well written.

**Comment by hmsjy2017** [comment]
@ryanfortner I have installed Caddy on the VPS, and it can be accessed normally and pass the test domain name.
https://apt.iamsjy.tk/

**Comment by ryanfortner** [comment]
> @ryanfortner I have installed Caddy on the VPS, and it can be accessed normally.

Awesome! What are your AAAA records, or CNAME?

Also, which VM?

**Comment by hmsjy2017** [comment]
@ryanfortner I used my own domain name to test. https://apt.iamsjy.tk/
Type: AAAA
Name: apt
Content: 2a09:11c0:335:ffff::2

> Also, which VM?

The VM used to synchronize the apt repository.

**Comment by hmsjy2017** [comment]
@ryanfortner Caddy is already configured. You only need to create an AAAA record to put it into use.

**Comment by hmsjy2017** [comment]
@ryanfortner Any progress?

**Comment by ryanfortner** [comment]
> @ryanfortner Any progress?

I've set up the domain.

**Comment by hmsjy2017** [comment]
Great! It works!

**Comment by hmsjy2017** [comment]
I think filebrowser may not be needed anymore, so it can be uninstalled.

In addition, the index.html in the repository is out of date and needs to be updated.

**Comment by ryanfortner** [comment]
> @ryanfortner I think the filebrowser may not be needed anymore, so it can be uninstalled.

I can uninstall it. 

> In addition, the index.html in the apt repository is out of date and needs to be updated.

👍

**Comment by ryanfortner** [comment]
I think this issue can be closed now. Please re-open if anything else comes up in relation to it
