### ISSUE TITLE
[Package submission]: onedriver

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#124]
### Package description

https://github.com/jstaf/onedriver
A native Linux filesystem for Microsoft OneDrive

### Licensing

GPL-3.0

### Packages

https://download.opensuse.org/repositories/home:/jstaf/Raspbian_10/armhf/onedriver_0.11.2-1_armhf.deb

Please keep this issue open. I will build an arm64 version when I have free time.

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.

**Comment by ryanfortner** [comment]
Let me know if you compile an arm64 version.

**Comment by hmsjy2017** [comment]
@ryanfortner I successfully compiled a deb package that supports arm64. It can be installed without problems.
https://github.com/hmsjy2017/onedriver-arm64-builds/releases/tag/v0.12.0

**Comment by ryanfortner** [comment]
> @ryanfortner I successfully compiled a deb package that supports arm64. It can be installed without problems. https://github.com/hmsjy2017/onedriver-arm64-builds/releases/tag/v0.12.0

I will add it to the next sync.

**Comment by hmsjy2017** [comment]
@ryanfortner Although it can be installed normally, when I run onedriver, the system prompts `onedriver: /lib/aarch64-linux-gnu/libc.so.6: version'GLIBC_2.32' not found (required by onedriver)`. I have submitted an issue to the official regarding this error. Please add the following deb package that can be used normally instead. https://launchpad.net/~jstaf/+archive/ubuntu/onedriver/+files/onedriver_0.11.1-1_arm64.deb

**Comment by ryanfortner** [comment]
> @ryanfortner Although it can be installed normally, when I run onedriver, the system prompts `onedriver: /lib/aarch64-linux-gnu/libc.so.6: version'GLIBC_2.32' not found (required by onedriver)`. I have submitted an issue to the official regarding this error. 
> 
> 
> 
> Please add the following deb package that can be used normally instead. https://launchpad.net/~jstaf/+archive/ubuntu/onedriver/+files/onedriver_0.11.1-1_arm64.deb

Are you using Debian Buster or Debian Bullseye?

Debian Bullseye has a higher libc version than buster, so it might work.

**Comment by hmsjy2017** [comment]
@ryanfortner I am using Debian Buster. The libc6 version of Debian Bullseye is 2.31, but the required version is 2.32. So it will not work.

**Comment by ryanfortner** [comment]
Onedriver has been added and will be synced to osdn within the next 24 hours, for now, it's in apt.raspbian-addons.org.

Do you mind writing [a script](http://github.com/raspbian-addons/scripts) for automatic update? see papirus-icon-theme's script for an example using a ppa.

**Comment by hmsjy2017** [comment]
@ryanfortner I created one.
https://github.com/raspbian-addons/scripts/pull/9

**Comment by hmsjy2017** [comment]
@ryanfortner I found that the armhf version has not been added. Can you add it?

**Comment by ryanfortner** [comment]
> @ryanfortner I created one. [raspbian-addons/scripts#9](https://github.com/raspbian-addons/scripts/pull/9)

Merged.

> @ryanfortner I found that the armhf version has not been added. Can you add it?

I will add it to the next sync.

**Comment by hmsjy2017** [comment]
@ryanfortner I built a new version to solve glibc version.
https://github.com/hmsjy2017/onedriver-arm64-builds/releases/tag/v0.12.0-fixed

**Comment by ryanfortner** [comment]
Added, thanks!
