### ISSUE TITLE
Create a logo for our project

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#125]
I think every project should have a logo for identification and promotion. Currently Raspbian Addons does not have its own logo.

**Comment by ryanfortner** [comment]
Good idea. Do you know anywhere to make one or someone who can?

**Comment by hmsjy2017** [comment]
I found that you added a favicon to the Raspbian Addons website. I think maybe it can be used as the logo of Raspbian Addons.

**Comment by ryanfortner** [comment]
> I found that you added a favicon to the Raspbian Addons website. I think maybe it can be used as the logo of Raspbian Addons.

Maybe. I don't think just a plain Raspberry Pi logo will work, I will look into creating one later.

**Comment by ryanfortner** [comment]
@hmsjy2017, I created this logo, what do you think?
![logo-test](https://user-images.githubusercontent.com/71036629/141795070-ce5851ff-bff7-4519-b97f-bb93ea30b400.png)

**Comment by hmsjy2017** [comment]
@ryanfortner Good job! But I think some changes need to be made. The distance between "Raspbian" and "Addons" should be larger. You can see that the letters p and d have been connected together, which will affect the appearance.

**Comment by ryanfortner** [comment]
> @ryanfortner Good job! But I think some changes need to be made. The distance between "Raspbian" and "Addons" should be larger. You can see that the letters p and d have been connected together, which will affect the appearance.

I've increased the spacing. Is this better?
![pi logo](https://user-images.githubusercontent.com/71036629/141810634-71409039-f00a-4987-ab7b-361195b6e9b2.png)

And the transparent background version: 
![22](https://user-images.githubusercontent.com/71036629/141810828-ffe7c6a7-51c1-4c94-b678-01be0ad7ca09.png)

**Comment by ryanfortner** [comment]
Also @hmsjy2017 , I've added the logo to the [main site](https://raspbian-addons.org), do you like it?

**Comment by hmsjy2017** [comment]
@ryanfortner Great! 👍

**Comment by ryanfortner** [comment]
@hmsjy2017 I've bolded the letters, so it looks a little better imo.. I don't have a way to get a higher resolution

**Comment by hmsjy2017** [comment]
@ryanfortner I think you can now add the logo to the project's GitHub profile and make some improvements to the GitHub profile.

**Comment by ryanfortner** [comment]
> @ryanfortner I think you can now add the logo to the project's GitHub profile and make some improvements to the GitHub profile.

I've added the logo. Should this issue be closed now?

**Comment by hmsjy2017** [comment]
@ryanfortner You can modify the display name of the organization on the settings page, and add the organization's Email, introduction, email, and URL. In addition, you can add the domain name of your organization and verify it in the "Verified & approved domains" tab.
