### ISSUE TITLE
Set up a mirror on SourceForge

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#128]
I tried to set up a mirror of Raspbian Addons on SourceForge.
https://sourceforge.net/projects/raspbian-addons/

You can add this apt repository to test it.
```
deb https://master.dl.sourceforge.net/project/raspbian-addons/debian/ /
```

It seems that it works well. But I may not be able to keep this mirror up to date.
In addition, I think we can also upload the repository backup to SourceForge.

**Comment by ryanfortner** [comment]
Looks good. Should I add it to the mirrorlist and scripts?

**Comment by hmsjy2017** [comment]
@ryanfortner I set up a scheduled task on the VPS hosting the apt repository to automatically synchronize the repository to SourceForge every 10 minutes.

**Comment by ryanfortner** [comment]
Added to [repo.py](https://github.com/raspbian-addons/scripts/blob/master/utils/repo.py).

**Comment by ryanfortner** [comment]
@hmsjy2017 can you add me to the project please? My username is `rkfortner-15`.

**Comment by hmsjy2017** [comment]
Added.
