### ISSUE TITLE
Use rsync to synchronize the apt repository

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#129]
@ryanfortner I found that using the scp command to synchronize files does not preserve the file creation time. This causes the time of the file to change with each synchronization.

In addition, the scp command seems to synchronize all files even if no files are modified, while rsync only synchronizes the modified files. Therefore, the speed of synchronization using the scp command will be slower than that of rsync.

In addition, rsync has much more functions than scp and most mirror sites use rsync to synchronize repositories. I think using rsync to synchronize repositories may be a better choice.

(PS: The parameter I used is `-avrt`.)

**Comment by ryanfortner** [comment]
Feel free to change the command with `crontab -e`

**Comment by hmsjy2017** [comment]
@ryanfortner Modified.
