### ISSUE TITLE
[Package submission]: hyperfine

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#130]
### Package description

A command-line benchmarking tool
https://github.com/sharkdp/hyperfine
![93787B52-80FE-4193-9941-998C099432CE](https://user-images.githubusercontent.com/42692274/143729750-60fc0a0d-c27c-4d7e-963a-80282f8de3ea.gif)

### Licensing

Apache

### Packages

https://github.com/sharkdp/hyperfine/releases/download/v1.12.0/hyperfine_1.12.0_arm64.deb
https://github.com/sharkdp/hyperfine/releases/download/v1.12.0/hyperfine_1.12.0_armhf.deb

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.

**Comment by ryanfortner** [comment]
Added to the auto-update script with commit [e6fac80](https://github.com/ryanfortner/au-sh/commit/e6fac80e071bac874daaa2c8cbd187abaf935f4c), it should appear in the repository within the next 24 hours.
