### ISSUE TITLE
[Package submission]: howdy

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#131]
### Package description

Windows Hello™ style facial authentication for Linux
https://github.com/boltgolt/howdy

### Licensing

MIT

### Packages

https://github.com/boltgolt/howdy/releases/download/v2.6.1/howdy_2.6.1.deb

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.

**Comment by ryanfortner** [comment]
Added.
