### ISSUE TITLE
[Package submission]: croc

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#132]
### Package description

Easily and securely send things from one computer to another
https://github.com/schollz/croc
![F1CD6D71-4C75-44BF-81FD-B482445366BB](https://user-images.githubusercontent.com/42692274/143729891-aa9bda08-1300-49e3-8ceb-59448257a783.gif)

### Licensing

MIT

### Packages

https://github.com/schollz/croc/releases/download/v9.5.0/croc_9.5.0_Linux-ARM.deb
https://github.com/schollz/croc/releases/download/v9.5.0/croc_9.5.0_Linux-ARM64.deb

### Notice

- [x] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.

**Comment by ryanfortner** [comment]
Added.
