### ISSUE TITLE
[Package submission]: pacstall

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#133]
### Package description

An AUR-inspired package manager for Ubuntu
https://github.com/pacstall/pacstall

### Licensing

GPL-3.0

### Packages

https://github.com/pacstall/pacstall/releases/download/1.6.1/pacstall-1.6.1.deb

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.

**Comment by ryanfortner** [comment]
Added.
