### ISSUE TITLE
[Package submission]: transfer

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#134]
### Package description

Large file transfer tool with multiple file transfer services support
https://github.com/Mikubill/transfer

### Licensing

MIT

### Packages

https://github.com/hmsjy2017/transfer-arm-packages/releases

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.

**Comment by ryanfortner** [comment]
Added
