### ISSUE TITLE
[Package submission]: Aria2 Pro Core

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#136]
### Package description

Aria2 static binaries for GNU/Linux with some powerful feature patches.
https://github.com/P3TERX/Aria2-Pro-Core

### Licensing

GPL-3.0

### Packages

https://github.com/hmsjy2017/Aria2-Pro-Core-debs/releases

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have tested this package and can confirm that it works on a Debian Buster system.

**Comment by ryanfortner** [comment]
Added.
