### ISSUE TITLE
[Package submission]: lazygit

### ISSUE THREAD

**Issue by ryanfortner** [raspbian-addons/raspbian-addons#137]
### Package description

![Gif](https://github.com/jesseduffield/lazygit/raw/assets/staging.gif)

simple terminal UI for git commands

### Licensing

MIT License

https://github.com/jesseduffield/lazygit/blob/master/LICENSE

### Packages

https://launchpad.net/~lazygit-team/+archive/ubuntu/release

opening this issue so i don't forget to add it.

**Comment by hmsjy2017** [comment]
Looks great.

**Comment by ryanfortner** [comment]
Added to the autoupdate script with commit [85a9c24](https://github.com/raspbian-addons/scripts/commit/85a9c24a99cc2409e24bc5d0146777b73b559571), but the VM hosting the repository has reached its maximum amount of github api requests for the hour. I will run the script again in a bit.

**Comment by ryanfortner** [comment]
Added.

**Comment by hmsjy2017** [comment]
@ryanfortner If you use an access token to authenticate GitHub, you can get far more API calls than when you are not authenticated.

https://docs.github.com/en/rest/overview/other-authentication-methods
