### ISSUE TITLE
[Package submission]: nali

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#138]
### Package description

An offline tool for querying IP geographic information and CDN provider.
https://github.com/zu1k/nali

### Licensing

MIT

### Packages

https://github.com/hmsjy2017/nali-debs/releases

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have tested this package and can confirm that it works on a Debian Buster system.

**Comment by ryanfortner** [comment]
Added.
