### ISSUE TITLE
apt-key is deprecated since Debian Bullseye (and Ubuntu 20.10)

### ISSUE THREAD

**Issue by Itai-Nelken** [raspbian-addons/raspbian-addons#139]
```
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
```
I think that means that gpg keys have to be placed in `/etc/apt/trusted.gpg.d`

**Comment by ryanfortner** [comment]
Does it still allow you to add the key, or is adding it disabled?

**Comment by Itai-Nelken** [comment]
It woeks, but will probably stop working in the future.

**Comment by ryanfortner** [comment]
I've pushed changes to [repo.py](https://github.com/raspbian-addons/scripts/commit/60e8a9c3b565bd2efce8ebd543319ecc65ec39dd), could you try uninstalling/reinstalling the repository again?

**Comment by Itai-Nelken** [comment]
I'll try it later this week, I'm not near my pi right now.

**Comment by ryanfortner** [comment]
any updates @Itai-Nelken ?

**Comment by hmsjy2017** [comment]
@ryanfortner It works.

**Comment by Itai-Nelken** [comment]
Works fine for me.
