### ISSUE TITLE
Rename opencv-4.5.1-org.pifan to opencv

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#140]
I modified the package name to a simpler one.
https://github.com/hmsjy2017/debs/releases/tag/opencv-4.5.1-arm64

**Comment by ryanfortner** [comment]
Added, thanks.

`build-essential, cmake, git, unzip, pkg-config, python3-pip` are compile dependencies and aren't needed for running the program itself. I have removed them from the control file. Here's the new deb link if you want to upload it to your repository: https://transfer.sh/get/Gut8ah/opencv_4.5.1_arm64.deb

**Comment by Itai-Nelken** [comment]
It might be a good idea to add a dummy package with the old name that depends on the new one but installs nothing.
