### ISSUE TITLE
Compile with arm64 VPS

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#142]
@ryanfortner I think it might be faster to compile with arm64 VPS. It seems that the VPS located in Boston is out of stock. So you can choose other regions such as Dallas.

**Comment by ryanfortner** [comment]
@hmsjy2017 is there any way we can get more storage for the repository-hosting vm? 32 gb is not going to work for much longer.

If we can get the storage increased, we can create multiple branches of the repository for each Debian release, and add larger packages and their dependencies.
