### ISSUE TITLE
[Package submission]: BBDown

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#143]
### Package description

 A command-line Bilibili Downloader.
 https://github.com/nilaoda/BBDown
![665E1E66-6C84-4E88-BB07-7AB33D14DA50](https://user-images.githubusercontent.com/42692274/145604615-17d050ce-1bc0-4378-9c14-3afbcb741802.gif)

### Licensing

MIT

### Packages

https://github.com/hmsjy2017/debs/releases/tag/bbdown-1.4.6-arm64

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have tested this package and can confirm that it works on a Debian Buster system.

**Comment by ryanfortner** [comment]
Added
