### ISSUE TITLE
[todo] package `temps`

### ISSUE THREAD

**Issue by ryanfortner** [raspbian-addons/raspbian-addons#148]
Binaries located here (only armv7l provided): https://github.com/musicpro/temps/releases/tag/0.7.4

**Comment by hmsjy2017** [comment]
@ryanfortner I tried to compile but failed due to many outdated dependencies.

**Comment by ryanfortner** [comment]
I think for now we should just publish the armhf version; here is the deb: https://transfer.sh/RUeooV/temps_0.7.4_armhf.deb

**Comment by ryanfortner** [comment]
added.
