### ISSUE TITLE
The `/root` directory of the VM used for building was emptied.

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#151]
@ryanfortner Last night I ssh to the VM used for building only to find that the `/root` directory was emptied. It seems that the `rm -rf *` command has been executed. However, there are some newly packaged and packaged software in this directory. I had to spend extra time to repackage these software. Do you know what happened?

**Comment by ryanfortner** [comment]
Oh no! I must have done that by accident, I'm sorry.

Are there any packages that were deleted that I can help you with? I'll be sure not to make this mistake again, sorry for the inconvenience...

**Comment by hmsjy2017** [comment]
@ryanfortner Fortunately, there is no particularly important data. The package aliyunpan and arm64 version of YesPlayMusic are backed up on my Raspberry Pi.

In order to avoid such accidents, I think we should be cautious in executing dangerous commands like `rm -rf *`. I think you can also create another v1.large VM for your compilation so that similar errors will not occur.

**Comment by ryanfortner** [comment]
I'll create another VM. At the time, I meant to delete all the contents in the `keepassxc-deb` folder but I realize I was not in that directory. Thanks for your patience :)
