### ISSUE TITLE
Question about dependencies

### ISSUE THREAD

**Issue by ryanfortner** [raspbian-addons/raspbian-addons#152]
@hmsjy2017 I noticed that the dependencies for your 7-zip packages are `libc6 (>= 2.17), libgcc1 (>= 1:3.0), libstdc++6 (>= 5)`. How did you find the libc/gcc version that's needed? Is there some way to automatically generate these dependencies?

**Comment by hmsjy2017** [comment]
@I found that p7zip's dependencies are these, so I think 7-Zip also needs these dependencies. In fact, I am not sure whether 7-Zip needs these dependencies.

**Comment by ryanfortner** [comment]
Well, in [this packagecloud article](https://blog.packagecloud.io/debian/debuild/packaging/2015/06/08/buildling-deb-packages-with-debuild/), the control file has a Depends line of:

`Depends: ${shlibs:Depends}, ${misc:Depends}`

I have not tested this, but I think it might automatically generate dependencies for binaries.

**Comment by ryanfortner** [comment]
Also, I might write a post on my [blog](https://ryanfortner.github.io/blog) about deb creation once I learn different methods of deb creation.
