### ISSUE TITLE
Setting up a Jenkins CI server

### ISSUE THREAD

**Issue by ryanfortner** [raspbian-addons/raspbian-addons#153]
I am trying to create a [Jenkins](https://www.jenkins.io/) server for repository build tasks, but I am having trouble getting the subdomain/dns record to work. I've set jenkins' port to 80, and `jenkins.raspbian-addons.org` DNS record to the ipv6 address of the vm, but I am still getting an `ERR_ADDRESS_UNREACHABLE` error. Do you have any idea what might be causing this, or if there are any alternative methods to get it working @hmsjy2017 ?

**Comment by hmsjy2017** [comment]
@ryanfortner It seems that Jenkins is not running.
```
jenkins.service - LSB: Start Jenkins at boot time
   Loaded: loaded (/etc/init.d/jenkins; generated)
Active: active (exited)since Wed 2021-12-15 14:50:47 UTC; 6min ago
Docs: man:systemd-sysv-generator(8)
   Tasks: 0 (limit: 4915)
   Memory: 0B
CGroup: /system.slice/jenkins.service

Dec 15 14:50:43 jenkins systemd[1]: Starting LSB: Start Jenkins at boot time...
Dec 15 14:50:44 jenkins jenkins[7012]: Correct java version found
Dec 15 14:50:45 jenkins su[7051]: (to jenkins) root on none
Dec 15 14:50:45 jenkins su[7051]: pam_unix(su-l:session): session opened for user jenkins by (uid=0)
Dec 15 14:50:46 jenkins su[7051]: pam_unix(su-l:session): session closed for user jenkins
Dec 15 14:50:47 jenkins jenkins[7012]: Starting Jenkins Automation Server: jenkins.
Dec 15 14:50:47 jenkins systemd[1]: Started LSB: Start Jenkins at boot time.
```

**Comment by hmsjy2017** [comment]
@ryanfortner I successfully run Jenkins through the WAR file. The path of the WAR file is `/opt/jenkins/jenkins.war`

**Comment by ryanfortner** [comment]
That’s great! I’ll go ahead and set it up through the web interface

**Comment by ryanfortner** [comment]
@hmsjy2017 have you set up admin credentials?

**Comment by hmsjy2017** [comment]
@ryanfortner I did’t change the password. The default password is in `/root/.jenkins/secrets/initialAdminPassword`. The default user is `admin`. In order to solve the "network unreachable" problem, I configured Cloudflare WARP to add IPv4 support to the VM.

**Comment by ryanfortner** [comment]
I think I'm just going to use `cron` and some bash scripts instead of jenkins for now, since I'm more familiar.
