### ISSUE TITLE
Main mirror (apt.raspbian-addons.org) inaccessible for now

### ISSUE THREAD

**Issue by ryanfortner** [raspbian-addons/raspbian-addons#155]
An edit I made to the autoupdate script caused issues with the main repository. I am downloading the repository from another mirror and it should be back up shortly. Some packages may not be available until the sync is complete. 

Also @hmsjy2017 , I’ve generated a new SSH key specifically for use with the repository VM. Could you add it to your SourceForge account so that syncs will still work please? (The public key is in /root/.ssh/id_ed25519.pub)

**Comment by ryanfortner** [comment]
The main mirror is back up.

**Comment by hmsjy2017** [comment]
@ryanfortner Added. In addition, you can apply for an account on SourceForge and I will add you to the project.

**Comment by ryanfortner** [comment]
Thanks!
