### ISSUE TITLE
[Package submission]: Icalingua

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#160]
### Package description

A Linux client for QQ and more
https://github.com/Icalingua/Icalingua

### Licensing

AGPL-3.0

### Packages

https://github.com/Icalingua/Icalingua/releases/download/v2.4.4-Deus-non-vult/icalingua_2.4.4-Deus-non-vult_arm64.deb

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have tested this package and can confirm that it works on a Debian Buster system.

**Comment by ryanfortner** [comment]
added to the autoupdate script with commit [c77a4ad](https://github.com/raspbian-addons/scripts/commit/c77a4ad6d1bc8e3500f7cb13cc4b9338d84b2fed)

**Comment by ryanfortner** [comment]
added
