### ISSUE TITLE
[Package submission]: Toybox

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#161]
### Package description

Toybox: all-in-one Linux command line.
https://landley.net/toybox/
https://github.com/landley/toybox

### Licensing

0BSD
https://github.com/landley/toybox/blob/master/LICENSE

### Packages

https://github.com/hmsjy2017/toybox-debs/releases

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have tested this package and can confirm that it works on a Debian Buster system.

**Comment by ryanfortner** [comment]
Are there any dependencies for this package?

**Comment by ryanfortner** [comment]
@hmsjy2017 , as we start to add more packages to automatic updates, would it be possible to create a GitHub actions to automatically compile and package software like toybox? I have created github actions for gitea and blockbench which are used by the repository, [here](https://github.com/ryanfortner/gitea-arm) and [here](https://github.com/ryanfortner/gitea-arm).
