### ISSUE TITLE
[Package submission]: .NET (arm64)

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#166]
### Package description

.NET is a free, cross-platform, open-source developer platform for building many different types of applications.

### Licensing

MIT

### .NET 6.0
https://dotnet.microsoft.com/en-us/download/dotnet/6.0
Packages: 
- SDK
- ASP.NET Core Runtime
- .NET Runtime

Both Arm64 and Arm32 are supposed. This means that we need to make 6 deb packages.

There are only deb packages for x64 in Microsoft's apt repository. But we can refer to their directory structure to package debs that support arm.
https://packages.microsoft.com/debian/11/prod/pool/main/d/
https://packages.microsoft.com/debian/11/prod/pool/main/a/

#### Dependencies
https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian#dependencies

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have tested this package and can confirm that it works on a Debian Buster system.

**Comment by hmsjy2017** [comment]
@ryanfortner Unfortunately, I currently don't have enough time to pack them. In addition, I lack experience in packaging complex software. I would be appreciate it if you could help me.

**Comment by ryanfortner** [comment]
According to the website you provided, the .net sdk provides all three runtimes.

![image](https://user-images.githubusercontent.com/71036629/147127548-01fd60cc-274f-4c2f-a5a4-2fbac0de57b3.png)

I've gone ahead and packaged and added all of the needed armhf debs. I'll package arm64 debs when I have time.

**Comment by hmsjy2017** [comment]
@ryanfortner In my opinion, the architecture of dotnet-runtime-deps-6.0 can be changed to `all` because it does not contain binary files.

**Comment by ryanfortner** [comment]
arm64 binaries: 

wget https://transfer.sh/get/hyDfzv/dotnet-apphost-pack-6.0_6_arm64.deb \
https://transfer.sh/get/1Tpisg/dotnet-host_6_arm64.deb \
https://transfer.sh/get/rCcXas/dotnet-hostfxr-6.0_6_arm64.deb \
https://transfer.sh/get/fkbq9N/dotnet-runtime-6.0_6_arm64.deb \
https://transfer.sh/get/6bd3wA/dotnet-sdk-6.0_6.0_arm64.deb \
https://transfer.sh/get/7oE4S0/dotnet-targeting-pack-6.0_6_arm64.deb

**Comment by ryanfortner** [comment]
Both the armhf and arm64 versions have been added.
