### ISSUE TITLE
[Package submission]: grype

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#167]
### Package description

https://github.com/anchore/grype
A vulnerability scanner for container images and filesystems
![3C242433-CF7D-42BD-B308-2E5947BAFDE8](https://user-images.githubusercontent.com/42692274/147354050-b8b8972b-14e0-472d-82e2-8a3bbc9ce375.gif)

### Licensing

Apache-2.0

### Packages

https://github.com/anchore/grype/releases

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have tested this package and can confirm that it works on a Debian Buster system.

**Comment by ryanfortner** [comment]
Added, thanks.
