### ISSUE TITLE
[Package submission]: fm

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#168]
### Package description

https://github.com/knipferrc/fm
A terminal based file manager
<img width="1285" alt="A21F830C-0AC6-44AC-92CD-E63AC1BCE703" src="https://user-images.githubusercontent.com/42692274/147355706-74adb1da-f75b-4516-b7f5-12bac451a830.png">

### Licensing

MIT

### Packages

https://github.com/knipferrc/fm/releases

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have tested this package and can confirm that it works on a Debian Buster system.

**Comment by ryanfortner** [comment]
Added, thanks
