### ISSUE TITLE
[Package submission]: Google Fonts

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#169]
### Package description

Font files available from Google Fonts
https://github.com/google/fonts

### Licensing

Most of the fonts in the collection use the [SIL Open Font License, v1.1](https://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web). Some fonts use the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). The Ubuntu fonts use the [Ubuntu Font License v1.0](https://ubuntu.com/legal/font-licence).

### Packages

http://bootes.ethz.ch/fonts/deb/

There are 1355 fonts in total and 466MB of disk space is required.

This zip file contains all the deb packages. https://github.com/hmsjy2017/fonts/releases/download/google-fonts/google-fonts.zip

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have tested this package and can confirm that it works on a Debian Buster system.

**Comment by ryanfortner** [comment]
Added.

**Comment by ryanfortner** [comment]
@hmsjy2017 could you open a pr on the [docs](https://github.com/raspbian-addons/docs) repository to add this to the package list please?

**Comment by hmsjy2017** [comment]
@ryanfortner Do I need to add every font? This may take a long time.

**Comment by ryanfortner** [comment]
> @ryanfortner Do I need to add every font? This may take a long time.

No, I don't think adding all of them is necessary, maybe just put 'fonts-*' as the packages name?

**Comment by hmsjy2017** [comment]
@ryanfortner Add. https://github.com/raspbian-addons/docs/pull/12
