### ISSUE TITLE
[Package submission]: AriaNg Native (armhf)

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#172]
### Package description

https://github.com/mayswind/AriaNg-Native
AriaNg Native is a desktop application built by Electron, containing full feature of AriaNg. You can run AriaNg Native on Windows or macOS without any browser. 
![5DEFB6B3-2996-484E-800D-5B8A165879AC](https://user-images.githubusercontent.com/42692274/147544335-30fc8b69-df17-477f-b430-e91f88bf1a3d.jpeg)

It works well on my Raspberry Pi.
### Licensing

MIT

### Packages

https://github.com/hmsjy2017/AriaNg-Native/releases

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have tested this package and can confirm that it works on a Debian Buster system.

**Comment by ryanfortner** [comment]
Added. Leaving this issue open until I compile an armhf version.

**Comment by ryanfortner** [comment]
https://transfer.sh/siJXzz/ariang-native_1.2.3_armv7l.deb

**Comment by ryanfortner** [comment]
added both versions.
