### ISSUE TITLE
[Package submission]: VeraCrypt

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#177]
### Package description

https://github.com/veracrypt/VeraCrypt
Disk encryption with strong security based on TrueCrypt

### Licensing

https://github.com/veracrypt/VeraCrypt/blob/master/License.txt

### Packages

https://www.veracrypt.fr/en/Downloads.html

### Notice

- [X] I have tested this package and can confirm that it works on a Debian Buster system.
- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.

**Comment by ryanfortner** [comment]
We have had issues with VeraCrypt in the past: https://github.com/raspbian-addons/raspbian-addons/issues/58

**Comment by hmsjy2017** [comment]
This problem seems to have been resolved. When I installed VeraCrypt, no software was uninstalled. Considering compatibility, we can add deb packages with "Debian-10" (which can run normally under bullseye).

**Comment by ryanfortner** [comment]
Added
