### ISSUE TITLE
[Package submission]: SwitchHosts

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#182]
### Package description

https://github.com/oldj/SwitchHosts
Switch hosts quickly!
![F1327480-AD94-4E3E-B43B-02A6A7426779](https://user-images.githubusercontent.com/42692274/147865136-7702c61e-8b23-4040-a298-ade7864a41dd.png)

### Licensing

Apache 2.0

### Packages

https://github.com/hmsjy2017/SwitchHosts/releases

### Notice

- [X] I have tested this package and can confirm that it works on a Debian Buster system.
- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have opened a pull request in the [docs repo](https://github.com/raspbian-addons/docs/), adding my package to the package list.

**Comment by ryanfortner** [comment]
Added.
