### ISSUE TITLE
[Package submission]: xmake

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#185]
### Package description

https://github.com/xmake-io/xmake
 A cross-platform build utility based on Lua

### Licensing

Apache 2.0

### Packages

https://github.com/hmsjy2017/xmake-debs/releases

### Notice

- [X] I have tested this package and can confirm that it works on a Debian Buster system.
- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have opened a pull request in the [docs repo](https://github.com/raspbian-addons/docs/), adding my package to the package list.

**Comment by hmsjy2017** [comment]
Script used for compilation:
https://github.com/xmake-io/xmake/blob/master/scripts/makepkg

**Comment by ryanfortner** [comment]
Added
