### ISSUE TITLE
[todo]: package Fondo

### ISSUE THREAD

**Issue by ryanfortner** [raspbian-addons/raspbian-addons#193]
Fondo is a wallpaper app for Linux.

I am working on getting it to work with debian Buster.

https://github.com/calo001/fondo

**Comment by ryanfortner** [comment]
Waiting on https://github.com/calo001/fondo/issues/182

**Comment by lucasgabmoreno** [comment]
> 

Have you tried installing Flatpack version for Debian?

Install Flatpack
https://flatpak.org/setup/Debian/

Install Fondo
https://flathub.org/apps/details/com.github.calo001.fondo

I have make [this issue](https://github.com/calo001/fondo/issues/182) beacuse I'm looking for non flatpack version.

**Comment by ryanfortner** [comment]
I haven't tried the flatpak version, I'm trying to create a debian package, which requires compiling the package from source.

**Comment by lucasgabmoreno** [comment]
I'm trying to do the same for Linux Mint.

Flatpack version works awesome but it's 1 GB and want better desktop integration, etc.
