### ISSUE TITLE
[Package submission]: vivaldi

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#196]
### Package description

https://vivaldi.com/
It's a browser with a bunch of clever features built-in. It's freakishly flexible and private too.

Vivaldi Browser Source Code 
https://vivaldi.com/source/

### Licensing

 Vivaldi is not made available under one unified open source license. It does contain the Chromium source code with changes made to allow the HTML/CSS/JS based UI to run. All changes to the Chromium source code are made available under a BSD license and can be read by anyone on vivaldi.com/source. 

https://help.vivaldi.com/desktop/privacy/is-vivaldi-open-source/

### Packages

https://downloads.vivaldi.com/stable/vivaldi-stable_5.0.2497.35-1_arm64.deb

https://downloads.vivaldi.com/stable/vivaldi-stable_5.0.2497.35-1_armhf.deb

### Notice

- [X] I have tested this package and can confirm that it works on a Debian Buster system.
- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have opened a pull request in the [docs repo](https://github.com/raspbian-addons/docs/), adding my package to the package list. 
https://github.com/raspbian-addons/docs/pull/15

**Comment by ryanfortner** [comment]
Added.

**Comment by ryanfortner** [comment]
Since vivaldi is based on chromium and is frequently updated, I think it's necessary to add it to the [autoupdate scripts](https://github.com/raspbian-addons/autoupdate).

However, since there is no way to get the latest version from the GitHub API like all the other scripts do, I'm not sure how we could achieve this.
