### ISSUE TITLE
[Package submission]: unsplash-wallpapers

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#198]
### Package description

https://github.com/soroushchehresa/unsplash-wallpapers
A cross-platform desktop application to set wallpapers from Unsplash built with Electron, React, and Redux
![61113341-C404-4350-977D-99AEF0526A16](https://user-images.githubusercontent.com/42692274/149361556-d14cea03-cab3-4259-8f29-fdc5b105e94d.gif)

### Licensing

MIT

### Packages

https://github.com/hmsjy2017/debs/releases/tag/unsplash-wallpapers_1.3.0_arm64

### Notice

- [X] I have tested this package and can confirm that it works on a Debian Buster system.
- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have opened a pull request in the [docs repo](https://github.com/raspbian-addons/docs/), adding my package to the package list.
https://github.com/raspbian-addons/docs/pull/16

**Comment by hmsjy2017** [comment]
It depends on libappindicator3-1 which is only in the stretch and buster repository. To be able to install it on bullseye, we can consider adding [libappindicator3-1](https://packages.debian.org/buster/libappindicator3-1) as well.

**Comment by ryanfortner** [comment]
> It depends on libappindicator3-1 which is only in the stretch and buster repository. To be able to install it on bullseye, we can consider adding [libappindicator3-1](https://packages.debian.org/buster/libappindicator3-1) as well.

According to [this post](https://www.reddit.com/r/debian/comments/pn1oia/what_happened_to_libappindicator31_in_debian_11/) and [this article](https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#noteworthy-obsolete-packages), libappindicator was replaced with `libayatana-appindicator`.

**Comment by hmsjy2017** [comment]
I replaced `libappindicator` with `libayatana-appindicator` in control and repackaged it.
https://github.com/hmsjy2017/debs/releases/download/unsplash-wallpapers_1.3.0_arm64/unsplash-wallpapers_1.3.0_arm64.deb

**Comment by ryanfortner** [comment]
added, and merged https://github.com/raspbian-addons/docs/pull/16.

Do you think it's necessary to open a pr on unsplash-wallpaper's official repo to change the libappindicator dependency to libayatana-appindicator?
