### ISSUE TITLE
[todo] update angryip scanner, add to autoupdate

### ISSUE THREAD

**Issue by ryanfortner** [raspbian-addons/raspbian-addons#202]
3.8.0

**Comment by ryanfortner** [comment]
This deb uses `zstd` as its compression type, which isn't supported in debian, so it will not be updated for now.

**Comment by hmsjy2017** [comment]
Ubuntu supports zstd compression and I successfully installed ipscan on it. So I thought it might be possible to repackage ipscan on Ubuntu.
