### ISSUE TITLE
Removing any DFW vm's

### ISSUE THREAD

**Issue by ryanfortner** [raspbian-addons/raspbian-addons#205]
<details>
<summary> Email from Hampton Moore of Fosshost </summary>

Hello!

Fosshost is decomissioning our Texas (DFW) AARCH64 POP. You are receiving this message because your project is impacted.
Please create new VM(s) ASAP (by Jan 31th) and migrate your data/services.

To ease the move, we've temporarily doubled your project's AARCH64 credits. This will allow you spin up new VM(s) at other AARCH64 POPs and migrate your data/services without shutting things in DWF down until you are finished.

Please remove your DFW VMs as soon as your migration is completed.

The DWF POP decommission wil be completed by January 31th at which time all remaining VMs will be stopped and related data will be deleted.

Please let us know immediately if you will have any concerns creating and moving to new VM(s) by this date, or If you have any questions whatever.

</details>

We only have one VM using the dfw POP, which is the one you use for testing and compiling software @hmsjy2017 .

![image](https://user-images.githubusercontent.com/71036629/150047569-24b78c24-b6be-46e9-84bf-e910d3dc8cfc.png)

If you are still using this VM, please migrate your data over to another one. If you aren't using it, please delete it before January 31st. Thanks!

**Comment by hmsjy2017** [comment]
@ryanfortner Removed.
