### ISSUE TITLE
Broken apt.raspbian-addons.org mirror again

### ISSUE THREAD

**Issue by ryanfortner** [raspbian-addons/raspbian-addons#206]
The main vm hosting the repository is broken again and I'm not sure why. It isn't accessible at all, I'm getting this error:
![image](https://user-images.githubusercontent.com/71036629/150153374-53df773b-eb2f-4cb4-902d-2c65a9b21f60.png)

Even after rebooting a few times via the console. Can you contact fosshost and see if they can help, or recover the data from it @hmsjy2017 ?

**Comment by hmsjy2017** [comment]
I have opened a ticket at https://support.fossho.st/.

****
Currently I am busy preparing for the final exam, so my leisure time is limited.

**Comment by ryanfortner** [comment]
> I have opened a ticket at https://support.fossho.st/.

Thanks! Please post any updates here if you're able to.

> Currently I am busy preparing for the final exam, so my leisure time is limited.

I understand. Thanks for your time :)

**Comment by hmsjy2017** [comment]
I found that the files in both the OSDN and SourceForge repositories are out of date. The latest update was on January 5th, and many of the new packages were not added.

**Comment by ryanfortner** [comment]
> I found that the files in both the OSDN and SourceForge repositories are out of date. The latest update was on January 5th, and many of the new packages were not added.

Yeah, I can see that... I also noticed that when trying to create a new VM, it appears it has no Internet access. I guess we should just wait for Fosshost's reply.

**Comment by ryanfortner** [comment]
> I think we can temporarily create a VM in London POP as an alternative server. It can be accessed.

I'll start setting it up now. I am not going to delete the old vm though, since it seems the entire Boston POP is having issues and not just our vm.

**Comment by hmsjy2017** [comment]
Currently this issue has been resolved. Thanks to Fosshost member Hampton Moore for the help!
![B1058F2B-BF2E-4B11-9A83-09B4FE941222](https://user-images.githubusercontent.com/42692274/150221318-c3ed5ed3-4ac6-45f4-a56a-6182cff293bc.jpeg)

**Comment by ryanfortner** [comment]
> Currently this issue has been resolved. Thanks to Fosshost member Hampton Moore for the help!
> ![B1058F2B-BF2E-4B11-9A83-09B4FE941222](https://user-images.githubusercontent.com/42692274/150221318-c3ed5ed3-4ac6-45f4-a56a-6182cff293bc.jpeg)

Thanks so much! I’ll switch back the dns records in a bit.
