### ISSUE TITLE
yarr

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#21]
https://github.com/nkanaev/yarr
yarr (yet another rss reader) is a web-based feed aggregator which can be used both as a desktop application and a personal self-hosted server.
![472B234D-0D0E-4142-B1EA-ADD4BC97E0E0](https://user-images.githubusercontent.com/42692274/120496176-f03c0f00-c3ef-11eb-8002-3a30bb351799.png)

**Comment by chunky-milk** [comment]
@hmsjy2017 are there deb files?

**Comment by hmsjy2017** [comment]
@chunky-milk Unfortunately, the project does not provide a deb package, and even the binary files that support arm are not provided. So we can only compile and package it ourselves.

**Comment by hmsjy2017** [comment]
[yarr.zip](https://github.com/chunky-milk/raspbian-addons/files/6586115/yarr.zip)

**Comment by chunky-milk** [comment]
> [yarr.zip](https://github.com/chunky-milk/raspbian-addons/files/6586115/yarr.zip)

Is that an arm64 or armv7 binary?

**Comment by hmsjy2017** [comment]
@chunky-milk armv7
It is easy to build.

**Comment by ryanfortner** [comment]
I've compiled it into a debs, they just need to be tested:

armv7l: https://transfer.sh/mNI0ze/yarr_2.2_armhf.deb

arm64: https://transfer.sh/qgMiXm/yarr_2.2_arm64.deb

When installed they should create a desktop entry also.

**Comment by ryanfortner** [comment]
Added.

https://apt.raspbian-addons.org/debian/pool/main/y/yarr/yarr_2.2_arm64.deb

https://apt.raspbian-addons.org/debian/pool/main/y/yarr/yarr_2.2_armhf.deb

**Comment by hmsjy2017** [comment]
@ryanfortner It does not seen to work well.
```
root@test:~# yarr
2021/12/08 14:48:11 main.go:88: using db file /root/.config/yarr/storage.db
2021/12/08 14:48:11 migration.go:28: db version is 0. migrating to 6
2021/12/08 14:48:11 migration.go:37: [migration:1] starting
2021/12/08 14:48:11 migration.go:63: [migration:1] failed to start transaction
2021/12/08 14:48:11 main.go:116: Failed to initialise database: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
```
