### ISSUE TITLE
Multi-user connection to VM via SSH Jump Server

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#211]
@ryanfortner According to the problem mentioned in https://github.com/raspbian-addons/raspbian-addons/issues/108#issuecomment-947857286 that ssh does not allow multiple users to connect to the VM at the same time, here is a perfect solution provided by Fosshost .

![B9888E77-B179-443E-A4BA-99C6EE3F3474](https://user-images.githubusercontent.com/42692274/150552297-ae1c8c51-981a-4b15-a289-9481109babaa.jpeg)
(IP address hidden for security reasons)

**Comment by ryanfortner** [comment]
This is really helpful, thanks :)
