### ISSUE TITLE
miniNodes provides free Raspberry Pi computing resources

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#213]
@ryanfortner  I'm excited to tell you that miniNodes has provided us with two Raspberry Pi (Model 4B, 8GB RAM, 64GB storage) nodes for testing and development (https://github.com/WorksOnArm/mininodes-arm-edge/issues/1). They are currently running the latest Raspberry Pi OS (armhf). In addition, it supports IPv4, which makes our compilation and testing a lot easier. I have emailed you the connection information.
Currently I am using node 2.

**Comment by ryanfortner** [comment]
This is great news! I've received your email with the credentials, thanks.

**Comment by yuandj** [comment]
很高兴，看到 TONY 复活啦，紧张的学业中，还能维护 GITHUB。因为网络不稳定，GITHUB 平时不太用，主要还是维护 GITEE 中文环境。

**Comment by yuandj** [comment]
很高兴，看到 TONY 复活啦，紧张的学业中，还能维护 GITHUB。因为网络不稳定，GITHUB 平时不太用，主要还是维护 GITEE 中文环境。

**Comment by yuandj** [comment]
石榴派开发环境也使用 4B+ 8GB RAM，32GB STORAGE。UBUNTU21.04 IOT  版本。
我现在用 RPI 官方镜像，16G STORAGE 做日常的 siger 编辑工作，GIMP 2.10 是主要的桌面图形处理程序，替代 PS。

**Comment by yuandj** [comment]
raspbian-addons 这仓是一键安装，DEB 仓的 所有软件吗？是否可以建立一个分支，有选择的安装呢？这也是石榴派希望实现的。

**Comment by yuandj** [comment]
GITEE 失联后，我去久违的趣无尽，看到你回归的消息，应该是放假了，和北京的同学活跃的时间差不多。看到你的GITHUB主页，果然复燃啦。[这是假期的活动，昨天晚上PR的](https://gitee.com/flame-ai/siger/commit/7200ac18a6c1483fed7888d312618d107c732bcd)。

**Comment by hmsjy2017** [comment]
> 很高兴，看到 TONY 复活啦，紧张的学业中，还能维护 GITHUB。因为网络不稳定，GITHUB 平时不太用，主要还是维护 GITEE 中文环境。

Raspbian Addons 是树莓派额外软件源，含有许多来自 GitHub 的开源软件，可作为对 Raspbian（Debian） 官方仓库的一个补充，你可以选择性地安装其中的软件。目前，我们通过自动更新脚本来使软件保持最新版本。想知道关于 apt 存储库的更多信息，可以参考文档：https://docs.raspbian-addons.org/about/how-does-it-work/ 。

Raspbian Addons is an additional repository for Raspberry Pi, containing many open source software from GitHub, as a supplement to the official Raspbian (Debian) repositories, from which you can optionally install software. Currently, we keep the software up-to-date with automatic update scripts. To know more about the apt repository, you can refer to the documentation: https://docs.raspbian-addons.org/about/how-does-it-work/ .
