### ISSUE TITLE
[Package submission]: markdownexplorer

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#214]
### Package description

https://github.com/jersou/markdown-explorer
Easily explore, view and edit markdown documentation of a file tree.
![68B5A5CF-E37C-4C38-9B36-00DD8ED2057A](https://user-images.githubusercontent.com/42692274/151114094-5b5848e0-ae16-4965-9e9d-d8c0410d7a09.png)
![47F62F39-90E1-46AE-B7C3-BEA5F0BD48F8](https://user-images.githubusercontent.com/42692274/151114161-b3cee966-2422-48b2-8650-fc11d8da4e29.png)

### Licensing

MIT

### Packages

https://github.com/hmsjy2017/debs/releases/download/MarkdownExplorer_0.1.1_arm64/MarkdownExplorer_0.1.1_arm64.deb

### Notice

- [X] I have tested this package and can confirm that it works on a Debian Buster system.
- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have opened a pull request in the [docs repo](https://github.com/raspbian-addons/docs/), adding my package to the package list. https://github.com/raspbian-addons/docs/pull/17

**Comment by ryanfortner** [comment]
Added and merged docs pr.
