### ISSUE TITLE
[Package submission]: ossutil

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#216]
### Package description

https://github.com/aliyun/ossutil

A user friendly command line tool to access AliCloud OSS.

### Licensing

MIT

### Packages

https://github.com/hmsjy2017/ossutil-debs/releases

### Notice

- [X] I have tested this package and can confirm that it works on a Debian Buster system.
- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have opened a pull request in the [docs repo](https://github.com/raspbian-addons/docs/), adding my package to the package list.
https://github.com/raspbian-addons/docs/pull/18

**Comment by ryanfortner** [comment]
Added and merged docs pr, thanks!
