### ISSUE TITLE
[Package submission]: ipsw

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#217]
### Package description

https://github.com/blacktop/ipsw
iOS/macOS Research Swiss Army Knife

### Licensing

MIT

### Packages

https://github.com/blacktop/ipsw/releases

### Notice

- [X] I have tested this package and can confirm that it works on a Debian Buster system.
- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have opened a pull request in the [docs repo](https://github.com/raspbian-addons/docs/), adding my package to the package list. https://github.com/raspbian-addons/docs/pull/19

**Comment by ryanfortner** [comment]
Added the arm64 package (there is no 32-bit arm binary). Can you create an [autoupdate script](https://github.com/raspbian-addons/autoupdate) for ipsw please?

**Comment by ryanfortner** [comment]
The script works, thanks!
