### ISSUE TITLE
[Package submission]: MinIO

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#218]
### Package description

https://github.com/minio/minio
High Performance, Kubernetes Native Object Storage

### Licensing

AGPL-3.0

### Packages

https://dl.min.io/server/minio/release/linux-arm64
https://dl.min.io/client/mc/release/linux-arm64

### Notice

- [X] I have tested this package and can confirm that it works on a Debian Buster system.
- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have opened a pull request in the [docs repo](https://github.com/raspbian-addons/docs/), adding my package to the package list.
 https://github.com/raspbian-addons/docs/pull/20

**Comment by ryanfortner** [comment]
I'm getting 404 error for https://dl.min.io/server/minio/release/minio_20220218015010.0.0_arm64.deb and https://dl.min.io/client/mc/release/mcli_20220223031559.0.0_arm64.deb...

**Comment by hmsjy2017** [comment]
@ryanfortner Sorry, I accidentally deleted the `/` at the end of the URL. Now it works.
https://dl.min.io/server/minio/release/linux-arm64/
https://dl.min.io/client/mc/release/linux-arm64/

**Comment by ryanfortner** [comment]
Added
