### ISSUE TITLE
Use the new link for installation script

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#219]
@ryanfortner Since jsDelivr is currently very unstable in Chinese mainland, the installation script is often unable to download. In order for Chinese mainland users to use our service normally, I recommend using the more stable GitHub Pages to host the download scripts and use the new installation link. Could you please enable the `Pages` feature for the `scripts` repository?

**Comment by ryanfortner** [comment]
Thanks for letting me know about this issue, I've set up github pages at https://scripts.raspbian-addons.org/. Feel free to open a pr on the docs to make the needed changes, or I can.

**Comment by hmsjy2017** [comment]
@ryanfortner In fact, it is also possible to use the default raspbian-addons.org. The link to the install script will be: https://raspbian-addons.org/scripts/utils/repo.py
