### ISSUE TITLE
[Package submission]: aliyun-cli

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#221]
### Package description

https://github.com/aliyun/aliyun-cli

The Alibaba Cloud CLI is a tool to manage and use Alibaba Cloud resources through a command line interface. It is written in Go and built on the top of Alibaba Cloud OpenAPI.

### Licensing

[Apache-2.0](https://github.com/aliyun/aliyun-cli/blob/master/LICENSE)

### Packages

https://github.com/hmsjy2017/aliyun-cli-debs/releases

### Notice

- [X] I have tested this package and can confirm that it works on a Debian Buster system.
- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have opened a pull request in the [docs repo](https://github.com/raspbian-addons/docs/), adding my package to the package list. https://github.com/raspbian-addons/docs/pull/21

**Comment by ryanfortner** [comment]
added and merged docs pr, thanks!
