### ISSUE TITLE
[Package submission]: aliyundrive-fuse

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#223]
### Package description

https://github.com/messense/aliyundrive-fuse
FUSE for AliyunDrive

### Licensing

MIT

### Packages

https://github.com/messense/aliyundrive-fuse/releases

### Notice

- [X] I have tested this package and can confirm that it works on a Debian Buster system.
- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have opened a pull request in the [docs repo](https://github.com/raspbian-addons/docs/), adding my package to the package list. https://github.com/raspbian-addons/docs/pull/25

**Comment by ryanfortner** [comment]
Since this package can be updated using the GitHub API, I think we can write an autoupdate script.

**Comment by hmsjy2017** [comment]
I am trying to write a script to update it automatically.

**Comment by hmsjy2017** [comment]
@ryanfortner Finished at https://github.com/raspbian-addons/autoupdate/pull/3.
