### ISSUE TITLE
[Package submission]: ferdi

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#224]
### Package description

https://github.com/getferdi/ferdi
Ferdi is a desktop app that helps you organize how you use your favourite apps by combining them into one application.

### Licensing

 Apache 2.0

### Packages

https://github.com/getferdi/ferdi/releases

### Notice

- [X] I have tested this package and can confirm that it works on a Debian Buster system.
- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have opened a pull request in the [docs repo](https://github.com/raspbian-addons/docs/), adding my package to the package list. https://github.com/raspbian-addons/docs/pull/26

**Comment by ryanfortner** [comment]
Added (autoupdate script [here](https://github.com/raspbian-addons/autoupdate/commit/4665db261e8ad530137d51d7a40e50ac3eee7e7a))
