### ISSUE TITLE
[Package submission]: Yank Note

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#225]
### Package description

https://github.com/purocean/yn
A Hackable Markdown Note Application for Programmers. Version control, documents encryption, code snippet running, integrated terminal, chart embedding, HTML applets, plug-in, and macro replacement.

### Licensing

 AGPL 3.0

### Packages

https://github.com/hmsjy2017/yn-arm/releases
Package name: `yank.note`

### Notice

- [X] I have tested this package and can confirm that it works on a Debian Buster system.
- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have opened a pull request in the [docs repo](https://github.com/raspbian-addons/docs/), adding my package to the package list. https://github.com/raspbian-addons/docs/pull/27

**Comment by ryanfortner** [comment]
Added and merged docs pr, thanks!
