### ISSUE TITLE
ipv4 connectivity on aarch64 vm's

### ISSUE THREAD

**Issue by ryanfortner** [raspbian-addons/raspbian-addons#226]
@hmsjy2017 do you know how to connect to ipv4 servers through the ipv6-only vms?

**Comment by ryanfortner** [comment]
Nevermind, I think I figured it out.

**Comment by hmsjy2017** [comment]
> @hmsjy2017 do you know how to connect to ipv4 servers through the ipv6-only vms?

My approach is to use Cloudflare WARP.
https://github.com/P3TERX/warp.sh
https://github.com/fscarmen/warp
