### ISSUE TITLE
Update Freetube to 0.16.0 (armhf)

### ISSUE THREAD

**Issue by Jai-JAP** [raspbian-addons/raspbian-addons#228]
https://github.com/FreeTubeApp/FreeTube/releases/download/v0.16.0-beta/freetube_0.16.0_arm64.deb

the above is the url for arm64 deb for freetube but armhf has to be compiled

**Comment by ryanfortner** [comment]
I would add freetube to our [autoupdate scripts](https://github.com/raspbian-addons/autoupdate), but the problem is that new versions of freetube are distributed through pre-releases, making it hard to use the github api to fetch the latest package. I can look into alternative solutions though.

Are you able to compile an armhf deb? I'm away from my pi right now.

**Comment by Jai-JAP** [comment]
I tried but got a lot of errors.
also i have my entrance exams next month so I have to prepare & get less time on pi

Anyway I will try tomorrow
If you have build instructions please forward I will try building
also forward build dependencies list if available

**Comment by ryanfortner** [comment]
Compiling has only worked on x86 linux for me, never got it to compile using the raspberry pi, but here are the steps.
```
1) git clone https://github.com/FreeTubeApp/FreeTube.git
2) cd FreeTube
3) npm install
4) patch the build script (I opened a pr around a month ago to fix it)
    - change line 23 of '_scripts/build.js' from if (args[3] === 'arm32') { to if (args[2] === 'arm32') {
5) run npm run build:arm32 
```

**Comment by Jai-JAP** [comment]
I am tonna try today

The patch appears to be applied
https://github.com/FreeTubeApp/FreeTube/blob/7bb030274e01cfd6b464d5b1824a0c7835353eb5/_scripts/build.js#L23

**Comment by theofficialgman** [comment]
> I would add freetube to our [autoupdate scripts](https://github.com/raspbian-addons/autoupdate), but the problem is that new versions of freetube are distributed through pre-releases, making it hard to use the github api to fetch the latest package. I can look into alternative solutions though. I have added the 0.16.0 arm64 version.

actually pre-releases are fine, I've just structured the get_release to ignore them

if you want a get_prerelease function can be added
```
get_prerelease() {
  curl --silent "https://api.github.com/repos/$1/releases" | jq -r 'map(select(.prerelease)) | first | .tag_name' | sed s/v//g
}
 ```
 
 for freetube, this returns `0.16.0-beta` which you will just have to massage a bit to remove the -beta for getting the deb filename

**Comment by theofficialgman** [comment]
^ done with https://github.com/Botspot/pi-apps/commit/6df111b0651d5170f249bd655f9648040abff6a4

**Comment by Jai-JAP** [comment]
I am currently building armhf deb 
publishing them soon

**Comment by Jai-JAP** [comment]
@ryanfortner @theofficialgman any suggestions where to upload the deb as transfer.sh does not seem to be working

**Comment by theofficialgman** [comment]
https://filebin.net/ is an option if you just want to share it temporarily

**Comment by Jai-JAP** [comment]
> Compiling has only worked on x86 linux for me, never got it to compile using the raspberry pi, but here are the steps. You'll need to have a recent version of npm installed for it to work
> 
> ```
> 1) git clone https://github.com/FreeTubeApp/FreeTube.git
> 2) cd FreeTube
> 3) npm install
> 4) patch the build script (I opened a pr around a month ago to fix it)
>     - change line 23 of '_scripts/build.js' from if (args[3] === 'arm32') { to if (args[2] === 'arm32') {
> 5) run npm run build:arm32 
> ```

@ryanfortner I successfully got this build compiled on a raspi4 however it took a long time

**Comment by Jai-JAP** [comment]
Here's the deb https://filebin.net/3qn6f6bkjcgbwk1m/freetube_0.16.0_armv7l.deb

**Comment by ryanfortner** [comment]
added, thanks!
