### ISSUE TITLE
[Package submission]: Hyper armhf

### ISSUE THREAD

**Issue by Jai-JAP** [raspbian-addons/raspbian-addons#229]
https://github.com/Jai-JAP/hyper-armhf-builds/releases/download/v3.2.0/hyper_3.2.0_armv7l.deb
Heres the armhf deb for Hyper terminal v3.2.0 confirmed working on Raspbian buster

**Comment by ryanfortner** [comment]
thanks so much! could you share the commands you used to compile it, so that I can add it to raspbian-addons autoupdate scripts?

**Comment by Jai-JAP** [comment]
I just compiled on my pi using same commands as listed on hyper GitHub page

**Comment by Jai-JAP** [comment]
Closinthis issue as solved
