### ISSUE TITLE
[bug]: Hyper arm64 broken

### ISSUE THREAD

**Issue by Jai-JAP** [raspbian-addons/raspbian-addons#230]
Hyper arm64 is broken as described [here](https://github.com/vercel/hyper/issues/6380) this issue occurs when its cross-compiled. I will compile it natively and post the deb soon

**Comment by Jai-JAP** [comment]
Here is the deb
 https://github.com/Jai-JAP/hyper-arm-builds/releases/download/v3.2.0/hyper_3.2.0_arm64.deb

**Comment by ryanfortner** [comment]
Added, thanks.
