### ISSUE TITLE
Remove the xTom’s mirrors

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#231]
xTom has removed the OSDN mirror (probably because it took up too much disk space). Therefore, we should remove them in the repo.py, speedtest.sh and mirrors repositories. Recently, I may not have enough time due to my busy schoolwork. Could you please help me? @ryanfortner

P.S.: speedtest.sh has bug that doesn't show download speed, but I don't know how to fix it.

**Comment by ryanfortner** [comment]
> xTom has removed the OSDN mirror (probably because it took up too much disk space). Therefore, we should remove them in the repo.py, speedtest.sh and mirrors repositories. Recently, I may not have enough time due to my busy schoolwork. Could you please help me? 

Done with commits `[01333e3](https://github.com/raspbian-addons/scripts/commit/01333e37cfe0306c8ca61a778780161d42408397)`, `[ad8d886](https://github.com/raspbian-addons/mirrors/commit/ad8d88692b47dfa81913d0cfd4421a27d01efd93)`, and `[678996b](https://github.com/raspbian-addons/status/commit/678996bd99a8e56ddb5f626a1d2e6d7e4719674e).

> P.S.: speedtest.sh has bug that doesn't show download speed, but I don't know how to fix it.

I'll take a look.
