### ISSUE TITLE
[Package submission]: Planet Launcher

### ISSUE THREAD

**Issue by leha-code** [raspbian-addons/raspbian-addons#233]
### Package description

A better  launcher that saves features for Minexraft Pi Modded

### Licensing

GPLv2

### Packages

https://github.com/mcpiscript/planet/releases

### Notice

- [X] I have tested this package and can confirm that it works on a Debian Buster system.
- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [x] I have opened a pull request in the [docs repo](https://github.com/raspbian-addons/docs/), adding my package to the package list.

**Comment by leha-code** [comment]
This will require the mcpi-reborn appimage to be either installed by hand or put into ~/.planet-launcher/minecraft.AppImage

**Comment by ryanfortner** [comment]
This looks cool! @leha-code do you think it could also be added to our [update](https://github.com/raspbian-addons/autoupdate) scripts for automatic updates?

**Comment by leha-code** [comment]
> This looks cool! @leha-code do you think it could also be added to our [update](https://github.com/raspbian-addons/autoupdate) scripts for automatic updates?

There is no URL for the latest build. However, the webcord script could be modified to work with this, as the releases are hosted on Github Releases.

**Comment by ryanfortner** [comment]
I have added your package. I'm also adding autoupdate scripts for this package to my todo list: https://github.com/raspbian-addons/raspbian-addons/issues/210

**Comment by ryanfortner** [comment]
Added to autoupdate scripts with [this commit](https://github.com/raspbian-addons/autoupdate/commit/9b72c8dfa238346a6c108fe8e320036dbe287195)
