### ISSUE TITLE
[bug]: Docker does not work on Pi 4 Node 2

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#234]
Docker on Raspberry Pi 4B Node 2 is not working properly. Could you please help me with this issue? @ryanfortner
 I've tried reinstalling Docker and installing an older version of Docker, but the issue is still not resolved. The following is the error message:
```
pi@raspberrypi:~ $ docker run -it debian
Unable to find image 'debian:latest' locally
latest: Pulling from library/debian
4a0c373b7fd8: Pull complete 
Digest: sha256:b42494c466d101bf06038e959e2e5acd227e1251987e79528e7d8b1f4040deaf
Status: Downloaded newer image for debian:latest
docker: Error response from daemon: failed to create endpoint tender_sutherland on network bridge: failed to add the host (veth6e060b4) <=> sandbox (veth301aa41) pair interfaces: operation not supported.
ERRO[0096] error waiting for container: context canceled
```

**Comment by ryanfortner** [comment]
@hmsjy2017 I found this: https://github.com/moby/moby/issues/27426 which suggests that the error is from an outdated/broken kernel. Could you try an apt update/upgrade and a reboot, then try the command again?

**Comment by hmsjy2017** [comment]
`linux-modules-extra-raspi` is not available on `bullseye`, it seems to be only available in Ubuntu's repositories.

**Comment by ryanfortner** [comment]
Try adding the user to the docker group and then rebooting. 
‘sudo usermod -aG docker $USER && sudo reboot’

**Comment by hmsjy2017** [comment]
@ryanfortner It works!  Thanks for helping me!

**Comment by ryanfortner** [comment]
> @ryanfortner It works! Thanks for helping me!

Great, I'm glad I could help :)
