### ISSUE TITLE
Update Tabby tqrminal (again) to v1.0.174

### ISSUE THREAD

**Issue by Jai-JAP** [raspbian-addons/raspbian-addons#236]
Here is the deb https://github.com/Jai-JAP/tabby-arm-builds/releases/download/v1.0.174/tabby-1.0.174-linux.deb
Changelog [here](https://github.com/Eugeny/tabby/releases/tag/v1.0.174)
I missed this release while publishing the build yesterday

**Comment by ryanfortner** [comment]
Added, thanks
