### ISSUE TITLE
[Package submission]: tea

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#240]
### Package description

A command line tool to interact with Gitea servers
https://gitea.com/gitea/tea

### Licensing

MIT

### Packages

https://github.com/hmsjy2017/tea-debs/releases

### Notice

- [X] I have tested this package and can confirm that it works on a Debian Buster system.
- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.
- [X] I have opened a pull request in the [docs repo](https://github.com/raspbian-addons/docs/), adding my package to the package list.https://github.com/raspbian-addons/docs/pull/30

**Comment by ryanfortner** [comment]
If this software is frequently updated, you should consider setting up a github action to automatically compile/package new releases.

**Comment by ryanfortner** [comment]
added.
