### ISSUE TITLE
Please update Snapdrop

### ISSUE THREAD

**Issue by Botspot** [raspbian-addons/raspbian-addons#244]
![2022-06-04-125259_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/172019663-44e45751-c5c4-4a6b-88df-9b09bf434128.png)

**Comment by ryanfortner** [comment]
Unfortunately I’m away from home and won’t be able to make new packages for a little while. 

In the meantime, feel free to run my script to make temporary debs: https://raw.githubusercontent.com/ryanfortner/snapdrop-rpi/master/snapdrop-updater.sh

**Comment by Botspot** [comment]
> Unfortunately I’m away from home and won’t be able to make new packages for a little while.

[The bus factor](https://en.wikipedia.org/wiki/Bus_factor) strikes again! I'm not sure who else has write access to this repo, but you may want to consider adding backup.
But don't feel rushed - this is a minor issue. Enjoy your trip.

**Comment by ryanfortner** [comment]
Debs have been updated in this repo and Pi-Apps.

**Comment by Botspot** [comment]
Thanks!
