### ISSUE TITLE
***IMPORTANT!!!*** Hosting provider shutting down

### ISSUE THREAD

**Issue by ryanfortner** [raspbian-addons/raspbian-addons#245]
Fosshost AARCH64, the hosting provider behind raspbian-addons, is shutting down due to reasons explained in [this document](https://cdn.discordapp.com/attachments/742089740643205174/1011718189903786054/23_Aug_CEO_Memo_-_Tenants_Update.pdf). Here is the announcement from the Fosshost discord server. 

```
To summarize (and for those of you on alternative platforms who can’t open the PDF): after months of silence and without consulting or preemptively advising the volunteers of Fosshost, Thomas, the CEO, has given you all under a business week to migrate your content off of our AARCH64 (arm64) platform. 

Additionally, if your domain is registered by Fosshost, it will not be renewed. Reach out and we can provide you with a transfer code.

At this time, x86 (Proxmox) is not undergoing any changes.

The volunteers of Fosshost had seen this track record of Thomas neglecting bills, and after he blocked access to our banking system for all other members of the org (specifically: other board of directors members responsible for handling our money), we expected something of this nature would occur. 

That said, we did not anticipate so short a window, and as we’re at this time powerless to change it, all we can say to you is: we’re sorry.
```

This means that by August 28, 2022:
- packages in raspbian-addons will no longer be updated
- the domain raspbian-addons.org will no longer exist

Our OSDN mirrors will remain online however they may not contain the most up-to-date packages as time goes on.

I offer all users my sincerest apologies.

**Comment by ryanfortner** [comment]
pinging @Itai-Nelken , @Botspot , @hmsjy2017 . please spread this information as you see fit.

**Comment by hmsjy2017** [comment]
@ryanfortner 
### For server:
#### Equinix Metal Arm64 Cluster
At this stage, the Equinix Metal ARM64 Cluster sponsored by ARM may be the best alternative.

#### Oracle Cloud
If you have a credit card, you may apply for Oracle Cloud's AlwayS Free Cloud Services, and you can create multiple ARM64 virtual machines for free.

#### Cheap Servers
Or we may be able to buy cheap servers such as RACKNERD, but they only provide the X86 server

### For domain name:
We can buy Raspbian-Addons.org after the domain name is unlocked. In order to save funds, we can also use free domain names provided by freenom or EU.org or buy cheap paid domain names.

**Comment by hmsjy2017** [comment]
@ryanfortner I think we need to do a backup of the important files of the servers as soon as possible (including the back-end scripts, SSH Keys) to migrate to a new hosting provider. And could you tell me how do you plan to deal with it?

**Comment by ryanfortner** [comment]
Here's what I'm going to do. 

- I'm applying for a Fosshost x86 server, which we will use to host the main mirror and autoupdate packages. Hopefully I can get this provisioned by Aug. 28.
- We will continue to use our [MiniNodes](https://github.com/WorksOnArm/mininodes-arm-edge) computing resources for compiling and packaging software.
- As for the raspbian-addons.org domain: fosshost has unlocked the domain and given me the transfer codes, however as I can't pay out of pocket for the domain, we will have to rely on donations. The price is around $10 per year to renew. My paypal is in the sponsor button of this repository and also [here](https://paypal.me/ryanfortner07).

**Comment by ryanfortner** [comment]
Update: thanks to the generosity of @hmsjy2017 and @Botspot , we have raised enough money for two years worth of domain renewal! Thankfully, crisis has been averted.
![image](https://user-images.githubusercontent.com/71036629/186978330-07392515-aa7e-4544-886e-67e3c97d651f.png)

I'll close this issue as soon as the processing finishes.

**Comment by oxmc** [comment]
I might be late, but if you ever need a host, I can host a site, and maybe pay for the domain (not sure on this one tho).

**Comment by ryanfortner** [comment]
I think we've got it covered for now. Thanks for the offer though.

**Comment by oxmc** [comment]
Alrighty, if you ever need it, the offer still stands.

**Comment by hmsjy2017** [comment]
I think the information at the top of the README can be removed as this issue has been resolved.

**Comment by ryanfortner** [comment]
> I think the information at the top of the README can be removed as this issue has been resolved.

Done with https://github.com/raspbian-addons/raspbian-addons/pull/247.
