### ISSUE TITLE
[bug]: Blockbench debs missing

### ISSUE THREAD

**Issue by Botspot** [raspbian-addons/raspbian-addons#246]
Is this a known issue?
```
$ version=4.3.1-384
$ wget https://apt.raspbian-addons.org/debian/pool/main/b/blockbench/blockbench_${version}_arm64.deb
--2022-09-19 15:02:39--  https://apt.raspbian-addons.org/debian/pool/main/b/blockbench/blockbench_4.3.1-384_arm64.deb
Resolving apt.raspbian-addons.org (apt.raspbian-addons.org)... 104.21.89.29, 172.67.136.143, 2606:4700:3037::ac43:888f, ...
Connecting to apt.raspbian-addons.org (apt.raspbian-addons.org)|104.21.89.29|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-09-19 15:02:40 ERROR 404: Not Found.

$ wget https://apt.raspbian-addons.org/debian/pool/main/b/blockbench/blockbench_${version}_armhf.deb
--2022-09-19 15:03:52--  https://apt.raspbian-addons.org/debian/pool/main/b/blockbench/blockbench_4.3.1-384_armhf.deb
Resolving apt.raspbian-addons.org (apt.raspbian-addons.org)... 172.67.136.143, 104.21.89.29, 2606:4700:3034::6815:591d, ...
Connecting to apt.raspbian-addons.org (apt.raspbian-addons.org)|172.67.136.143|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-09-19 15:03:52 ERROR 404: Not Found.
```

**Comment by ryanfortner** [comment]
It looks like the auto updater for the repository failed, I’ll fix it in a bit since I’m not near my computer right now.

**Comment by ryanfortner** [comment]
It looks like the latest version in the repository is [4.4.1-389](https://apt.raspbian-addons.org/debian/pool/main/b/blockbench/). Unfortunately, when the auto-updater runs, old packages are automatically removed to conserve storage on the hosting VM.

I [just ran](https://github.com/Botspot/pi-apps/pull/2135) the Pi-apps updater action. Try installing Blockbench again.

**Comment by Botspot** [comment]
> Unfortunately, when the auto-updater runs, old packages are automatically removed to conserve storage on the hosting VM.

While I understand this is standard practice for an apt repo, whereby if users encounter missing packages they are instructed by apt to run `sudo apt update`, Pi-Apps has no equivalent mechanism like that.

Compounded by the fact that we now only update Pi-Apps on a weekly basis, (It used to be every 6 hours), and the likelihood for a real user to encounter an outdated version number increases significantly.

I propose that one of the following solutions be implemented:
- Change the raspbian-addons script to retain old debs with a grace period of two weeks. At any one time this should not increase storage capacity by much.
- Change the Pi-Apps scripts that use raspbian-addons to, rather than directly install deb packages straight from a URL, setup the raspbian-addons repository and install the package name, allowing future upgrades to be carried out by `apt`.
- Change the Pi-Apps scripts that use raspbian-addons to intelligently detect and install the correct version number, but a hardcoded version number is also left as an unused comment in the script to allow future updates to trigger a reinstall (and upgrade) from the Pi-Apps side of things.

**Comment by ryanfortner** [comment]
I understand your concern, and I prefer options 2 and 3 as well. However I'm quite busy at the moment as well, but I can add to my to-do list for a weekend :)
