### ISSUE TITLE
Add Tor Browser

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#4]
https://sourceforge.net/projects/tor-browser-ports/
UNOFFICIAL builds of Tor Browser for architectures not (yet) provided by the Tor Project. Currently, ARM architecture Linux builds for 32-bit armv7 (armhf) and 64-bit aarch64 (arm64) are available.

**Comment by chunky-milk** [comment]
> https://sourceforge.net/projects/tor-browser-ports/
> UNOFFICIAL builds of Tor Browser for architectures not (yet) provided by the Tor Project. Currently, ARM architecture Linux builds for 32-bit armv7 (armhf) and 64-bit aarch64 (arm64) are available.

I will add the builds after I finish packaging them into debs.

**Comment by chunky-milk** [comment]
@hmsjy2017 I have added en-US tor-browser package for armhf, try installing it with `sudo apt update && sudo apt install tor-browser`

**Comment by hmsjy2017** [comment]
@chunky-milk All right. In addition, would you like to create a zh-CN version as well?

**Comment by hmsjy2017** [comment]
@chunky-milk Does it work properly now? I see it in the OSDN repository now.

**Comment by chunky-milk** [comment]
> @chunky-milk Does it work properly now? I see it in the OSDN repository now.

I haven't added working tor browser builds yet. It's on my to do list though.

**Comment by hmsjy2017** [comment]
@chunky-milk Which should we use? 
https://osdn.net/projects/raspbian-addons/storage/
https://osdn.net/projects/raspbian-addons/storage/raspbian-addons/

**Comment by chunky-milk** [comment]
> @chunky-milk Which should we use? 
> 
> https://osdn.net/projects/raspbian-addons/storage/
> 
> https://osdn.net/projects/raspbian-addons/storage/raspbian-addons/

Do you know if there's a difference between the two? If there isn't, then probably https://osdn.net/projects/raspbian-addons/storage/

**Comment by hmsjy2017** [comment]
@chunky-milk It seems that the files inside are more recent.
https://osdn.net/projects/raspbian-addons/storage/raspbian-addons/

But I think it is better to push the file here, because "raspbian-addons" is not necessary to repeat in the link.
https://osdn.net/projects/raspbian-addons/storage/

**Comment by chunky-milk** [comment]
> @chunky-milk It depends on which directory you push the file to.
> 
> It seems that the files inside are more recent.
> 
> https://osdn.net/projects/raspbian-addons/storage/raspbian-addons/
> 
> 
> 
> But I think it is better to push the file here, because "raspbian-addons" is not necessary to repeat in the link.
> 
> https://osdn.net/projects/raspbian-addons/storage/

Ok. I am currently uploading files so I will make the changes when the upload finishes.

**Comment by hmsjy2017** [comment]
@chunky-milk I think it is necessary to modify repo.sh, because GitHub is no longer used to host the apt repository. In addition, I think it is a good idea to list all available mirrors when executing the script and let users choose by themselves.

**Comment by chunky-milk** [comment]
> @chunky-milk I think it is necessary to modify repo.sh, because GitHub is no longer used to host the apt repository. In addition, I think it is a good idea to list all available mirrors when executing the script and let users choose by themselves.

Yes, I am planning on updating the script soon. I am out of town until Monday so I will not be able to edit the script until then

**Comment by hmsjy2017** [comment]
The official deb packages are available now.
https://deb.torproject.org/torproject.org/pool/main/t/tor/

**Comment by ryanfortner** [comment]
@hmsjy2017

**Comment by hmsjy2017** [comment]
@ryanfortner They have been added to the official Debian repository, so I don't think it is necessary to add them.一
