### ISSUE TITLE
Uninstallable packages

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#57]
Device: Raspberry Pi 4B
Operating system: 2021-05-07-raspios-buster-arm64
I tried to install all the software in this repository, but some seem to be unable to install.

Here is a list of them:

Unable to locate package
- cgal
- com.github.libredeb.lightpad
- halo-weather
- openrazer
- python3-stdlib-extensions

Unable to install due to dependency issues
- xapp
- conky-manager:armhf
- duckstation:armhf
- piserver
- python3.9
- qt5-opengl-dev:armhf
- qt5-opengl-qtcreator:armhf
- razergenie:armhf
- Remarkable
- sticky
- ungoogled-chromium
- warpinator
I only tested it on arm64, so I don't know if they can be installed on armhf.

```
E: Unable to locate package cgal
E: Unable to locate the package com.github.libredeb.lightpad
E: Unable to find any packages according to glob ‘com.github.libredeb.lightpad’
E: Cannot find any software package according to the regular expression com.github.libredeb.lightpad
E: Unable to locate the package halo-weather
E: Unable to locate the package openrazer
E: Unable to locate the package python3-stdlib-extensions
E: Unable to locate the package xapp

The following packages have unmet dependencies:
 conky-manager:armhf: depends on: realpath:armhf but cannot install it
                       Dependency: conky:armhf but unable to install it
                       Dependency: p7zip-full:armhf but it will not be installed
 duckstation:armhf: Dependency: libsdl2-dev:armhf but it will not be installed
 piserver: dependency: qemu-user-static
 python3.9: Dependency: python3.9-minimal (= 3.9.5-3) but it will not be installed
             Dependency: libpython3.9-stdlib (= 3.9.5-3) but it will not be installed
 qt5-opengl-dev:armhf: Dependency: build-essential:armhf but it will not be installed
                        Dependency: libraspberrypi-dev:armhf but it will not be installed
 qt5-opengl-qtcreator:armhf: Dependency: build-essential:armhf but it will not be installed
 razergenie:armhf: Dependency: openrazer-daemon:armhf but cannot install it
 Remarkable: Dependency: gir1.2-webkit-3.0 but unable to install it
 sticky: dependency: gir1.2-xapp-1.0 (>= 2.2.0) but 1.2.2-1 is about to be installed
          Dependency: python3-xapp (>= 2.2.0) but it will not be installed
 ungoogled-chromium: Dependency: ungoogled-chromium-common (= 90.0.4430.93-1.buster1) but it will not be installed
 warpinator: dependency: gir1.2-xapp-1.0 (>= 1.6.0) but 1.2.2-1 is about to be installed
              Dependency: python3-xapp (>= 1.6.0) but it will not be installed
E: The error cannot be corrected, because you require certain software packages to maintain the status quo, that is, they break the dependencies between the software packages
```

**Comment by hmsjy2017** [comment]
In addition, python-pip cannot be installed normally due to dependency problems.

**Comment by hmsjy2017** [comment]
Webcord and goreleaser cannot be installed either. It seems that they haven't synchronized to OSDN.
```
Error: 1 https://mirror.sjtu.edu.cn/raspbian-addons/debian buster/main arm64 webcord arm64 1.5.0
   404 Not Found [IP: 111.186.58.212 443]
Error: 2 https://mirror.sjtu.edu.cn/raspbian-addons/debian buster/main arm64 goreleaser arm64 0.172.1
   404 Not Found [IP: 111.186.58.212 443]
E: Cannot download https://mirror.sjtu.edu.cn/raspbian-addons/debian/pool/main/w/webcord/webcord_1.5.0_arm64.deb 404 Not Found [IP: 111.186.58.212 443]
E: Cannot download https://mirror.sjtu.edu.cn/raspbian-addons/debian/pool/main/g/goreleaser/goreleaser_0.172.1_arm64.deb 404 Not Found [IP: 111.186.58.212 443]
```

**Comment by hmsjy2017** [comment]
Although these packages can be installed, errors will occur:
(Tested on arm64 Linux)
syncthing-relaysrv
appimagelauncher
box86:armhf
openresty
openresty-opm
openresty-resty

**Comment by Itai-Nelken** [comment]
The box86 problem is something wring with binfmy on your system, try running `sudo systemctl restart systemd-binftmt`, if that works, then something is w4ong with the deb, else its your system.

**Comment by Itai-Nelken** [comment]
For remarkable-check the pi-apps install64 script for links to all the dependencies. For armhf I found them but tge file is on a different sd card I can't access right now.

**Comment by chunky-milk** [comment]
All of the packages that had a 404 Not Found error should be fixed now.

**Comment by ryanfortner** [comment]
Sorry it took so long to address these package issues.

First of all, installing `armhf` packages on `arm64` devices can be very tricky at times. Sometimes using multiarch will work flawlessly, most times they won't work at all or end up with never-ending dependency lists. I can't promise any packages in this repository will work with multiarch, use it as your own risk. (I will add a warning to the readme shortly).

Second of all, if a package requests the installation of another, add it to the install command. For example:

The error @hmsjy2017 received for ungoogled-chromium was the following: `ungoogled-chromium: Dependency: ungoogled-chromium-common (= 90.0.4430.93-1.buster1) but it will not be installed`. So, try again, adding ungoogled-chromium-common to the command. `sudo apt install ungoogled-chromium ungoogled-chromium-common`. If you keep getting dependency requests like this, just keep adding them to the command.

Finally, if you get to the point where a package is being installed on the proper architecture, NOT multiarch, and you get still get an `unable to install` error, then it should be reported.

I will push some changes to the [docs repository](https://docs.raspbian-addons.org) soon, explaining all of this in more detail.

BTW, @Crilum , it seems like the Deskreen deb isn't recognized as a package... I'm going to remove it from the repository until it can be recompiled successfully.

**Comment by Crilum** [comment]
Thanks.

**Comment by ryanfortner** [comment]
@hmsjy2017 As for the packages that can be installed, but cannot be configured, this is a problem on your end.

- Seems like box86 binfmt settings are conflicting with appimagelauncher's binfmt settings. Try installing them one at a time, and see if it changes anything.
- OpenResty can't be installed because it's default port is already in use. Do you have any other software which is using the port 80? (since the core openresty package fails to configure, all its other packages also fail).

**Comment by hmsjy2017** [comment]
@ryanfortner However, I can install Deskreen normally on the latest RPiOS and Debian. There seems to be no problem.

**Comment by ryanfortner** [comment]
> @ryanfortner However, I can install Deskreen normally on the latest RPiOS and Debian. There seems to be no problem.

It installs on armhf? Or just arm64

**Comment by hmsjy2017** [comment]
I only tested on arm64.

**Comment by ryanfortner** [comment]
> I only tested on arm64.

Ok. The armhf deb seems to be the problem.

**Comment by ryanfortner** [comment]
Can I close this issue now?
