### ISSUE TITLE
Automatically updated packages

### ISSUE THREAD

**Issue by ryanfortner** [raspbian-addons/raspbian-addons#79]
Each day, the hosting vm will download [this script](https://raw.githubusercontent.com/raspbian-addons/scripts/master/au-rewrite.sh) and execute it, automatically updating some packages.

This saves the repository maintainters time so that we don't have to manually add as many packages.

If you notice that a package is missing, or the script has failed, please let me know.

**Comment by ryanfortner** [comment]
VSCodium has been added to auto update.

**Comment by ryanfortner** [comment]
Many packages have been added to autoupdate, including the following, as well as others not mentioned:

- hyperfine
- howdy
- pacstall
- croc
- turbowarp-desktop
- code-server
- electron-fiddle
- papirus-icon-theme
- lazygit
- webcord
- gh
- tut
- box64
- box86

**Comment by cycool29** [comment]
https://github.com/Botspot/pi-apps/pull/1059#issuecomment-988490871 @ryanfortner
