### ISSUE TITLE
Create a website for Raspbian Addons

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#88]
Raspbian Addons does not have an official website currently. I think we can create one.

**Comment by hmsjy2017** [comment]
I created one for test.
https://github.com/hmsjy2017/raspbian-addons-website
It is modified from pi-ware’s website.

**Comment by chunky-milk** [comment]
Great idea! I'll make some modifications later. I enabled github pages at https://raspbian-addons.github.io/ .

**Comment by ryanfortner** [comment]
Closing now.
