### ISSUE TITLE
armv7l Microsoft build of OpenJDK

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#9]
Download page: https://www.microsoft.com/openjdk
https://aka.ms/download-jdk/microsoft-jdk-16.0.1.9.1-linux-aarch64.tar.gz
Can it be packaged into a deb package for installation?

**Comment by chunky-milk** [comment]
> Download page: https://www.microsoft.com/openjdk
> https://aka.ms/download-jdk/microsoft-jdk-16.0.1.9.1-linux-aarch64.tar.gz
> Can it be packaged into a deb package for installation?

Sure, **if it's allowed to be distributed.**

**Comment by hmsjy2017** [comment]
@chunky-milk It is also published on GitHub, and I think it is allowed to be distributed.
https://github.com/microsoft/openjdk-aarch64/releases

**Comment by hmsjy2017** [comment]
@chunky-milk https://github.com/microsoft/openjdk/discussions/2#discussioncomment-575926

**Comment by chunky-milk** [comment]
@hmsjy2017 I am building the package right now. Are there any `armv7l` builds?

**Comment by hmsjy2017** [comment]
@chunky-milk No, but we can try to compile it.

**Comment by chunky-milk** [comment]
I am leaving this issue open in case someone comes along and successfully comes along and compiles it for 32-bit arm
