### ISSUE TITLE
[Package submission]: Notion Repackaged 

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#91]
### Package description

Notion Desktop builds with Notion Enhancer for Windows, MacOS and Linux. 
https://github.com/notion-enhancer/notion-repackaged

### Licensing

MIT

### Packages

https://github.com/notion-enhancer/notion-repackaged/releases
(arm64)

### Notice

- [x] I have confirmed that this package has never been discussed in https://github.com/chunky-milk/raspbian-addons/issues, nor in the package list.

**Comment by ryanfortner** [comment]
Added the 'notion-app-enhanced' package.
