### ISSUE TITLE
[Package submission]: Xournal++

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#96]
### Package description

https://github.com/xournalpp/xournalpp
Xournal++ is a handwriting notetaking software with PDF annotation support. Written in C++ with GTK3, supporting Linux (e.g. Ubuntu, Debian, Arch, SUSE), macOS and Windows 10. Supports pen input from devices such as Wacom Tablets.
![1B6B359C-848B-439F-B43A-1C03698EC90B](https://user-images.githubusercontent.com/42692274/135724163-d5575c90-32cf-4f8e-9c21-a380cf7ab1bc.png)

### Licensing

GPLv2

### Packages

https://launchpad.net/~andreasbutti/+archive/ubuntu/xournalpp-master/+packages
latest: https://launchpad.net/~andreasbutti/+archive/ubuntu/xournalpp-master/+files/xournalpp_1.1.0+dev+dev~202109271025~ubuntu21.10.1_arm64.deb

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.

**Comment by ryanfortner** [comment]
Added
