### ISSUE TITLE
[Package submission]: musikcube

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#97]
### Package description

https://github.com/clangen/musikcube
a cross-platform, terminal-based music player, audio engine, metadata indexer, and server in c++

![69D9F9F2-B33E-4628-9FC5-7F9E9CF0E573](https://user-images.githubusercontent.com/42692274/135724706-2af39fe4-a463-4d9b-b3d8-7920974e0a44.png)

### Licensing

BSD-3-Clause 

### Packages

https://github.com/clangen/musikcube/releases/download/0.96.6/musikcube_0.96.6_debian_buster_raspberrypi_armhf.deb

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.

**Comment by ryanfortner** [comment]
Added
