### ISSUE TITLE
[Package submission]: Albert

### ISSUE THREAD

**Issue by hmsjy2017** [raspbian-addons/raspbian-addons#98]
### Package description

https://github.com/albertlauncher/albert
A fast and flexible keyboard launcher
![BE4C8287-194A-4B19-A654-7AF6F6C6CE9B](https://user-images.githubusercontent.com/42692274/135725107-9ac4285d-f8f4-4315-ab6e-33a024a60109.jpeg)

### Licensing

No description

### Packages

https://software.opensuse.org/download.html?project=home:manuelschneid3r&package=albert

### Notice

- [X] I have confirmed that this package has never been discussed in https://github.com/raspbian-addons/raspbian-addons/issues, nor in the package list.

**Comment by ryanfortner** [comment]
Added, as well as the 'albert-dbgsym' package.
